# Generated by Django 2.0.1 on 2018-02-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
    ]
