# Generated by Django 2.0.1 on 2018-02-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_photos'),
        ('photos', '0003_photo_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(to='albums.Album'),
        ),
    ]
