# Generated by Django 2.0.1 on 2018-03-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='local_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
