# Generated by Django 2.0.1 on 2018-03-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo_local_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='local_filename',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
